CREATE TABLE [dbo].[Status](
	[Status_id] [int] IDENTITY(1,1) NOT NULL,
	[Status_name] NVARCHAR(50) NOT NULL,
	[Status_seq] [int] NULL,
 CONSTRAINT [PK_Status_1] PRIMARY KEY CLUSTERED 
(
	[Status_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
