CREATE TABLE [dbo].[SuppyAddress](
	[myPoint_id] [int] NOT NULL,
 CONSTRAINT [PK_SuppyAddress] PRIMARY KEY CLUSTERED 
(
	[myPoint_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
